/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JFrame;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.LinkedList;
import java.util.Queue;
import java.util.HashSet;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class Menu_Principal extends javax.swing.JFrame {

     private String municipioActual = null;
    private final Color HIGHLIGHT_COLOR = new Color(19, 144, 7); // Transparencia añadida
    private BufferedImage mapImage;
    private BufferedImage bordersImage; // Imagen para detección de bordes
    private BufferedImage highlightedImage;
    private Map<Point, String> puntosDeMunicipio = new HashMap<>();
    private int currentX, currentY; // Posición actual del mouse
    private boolean controlKeyPressed = false; // Variable para rastrear el estado de la tecla Control
    
    // Panel flotante para mostrar información del municipio
    private JPanel panelFlotante;
    private JLabel labelNombreMunicipio;
    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        //richard es gay
        //jammy es prosti
        //kjrgkljdsgfdfj
        //jhfkjhedkjf
        
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initializeMapa();
        setupKeyListener();
        crearPanelFlotante();
    }
    private void crearPanelFlotante() {
        // Crear el panel flotante
        panelFlotante = new JPanel();
        panelFlotante.setLayout(new BorderLayout());
        panelFlotante.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(70, 70, 70, 200), 1),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
        // Fondo negro semitransparente (el último valor 180 es la transparencia, máximo 255)
        panelFlotante.setBackground(new Color(0, 0, 0, 180));
        
        // Etiqueta para el nombre del municipio con texto blanco
        labelNombreMunicipio = new JLabel();
        labelNombreMunicipio.setFont(new Font("Segoe UI", Font.BOLD, 14));
        labelNombreMunicipio.setForeground(Color.WHITE);
        
        panelFlotante.add(labelNombreMunicipio, BorderLayout.CENTER);
        panelFlotante.setVisible(false); // Inicialmente invisible
        
        // Establecer un tamaño preferido para el panel
        panelFlotante.setPreferredSize(new Dimension(150, 30));
        
        // Agregar el panel a la capa de cristal del JFrame
        this.getLayeredPane().add(panelFlotante, JLayeredPane.POPUP_LAYER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bandera_Caqueta.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 160, 110));

        jLabel2.setText("Caquetá - Paraíso Natural");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 620, 110));

        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 20, 60, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("jLabel4");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextField1.setText("jTextField1");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, 400, 180));

        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, 400, 370));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 400, 60));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel8.setText("MAPA POLITICO DEL CAQUETA");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 596, 280, 110));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MUNICIPIOS (1).png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 840, 580));

        jLabel9.setText("LOGO");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void initializeMapa() {
        try {
            // Cargar la imagen del mapa
            mapImage = ImageIO.read(getClass().getResource("/img/WhatsApp Image 2025-04-02 at 4.14.08 PM"));
            highlightedImage = new BufferedImage(mapImage.getWidth(), mapImage.getHeight(), BufferedImage.TYPE_INT_ARGB);
            
            // Procesar la imagen para detectar bordes
            bordersImage = detectarBordes(mapImage);
            
            // Definir los puntos de los municipios
            
            puntosDeMunicipio.put(new Point(299, 205), "S. Visente del Caguàn");
            puntosDeMunicipio.put(new Point(236, 78),  "S. Visente del Caguàn");

            
            puntosDeMunicipio.put(new Point(174, 164), "El Doncello");
            puntosDeMunicipio.put(new Point(201, 210), "El Doncello");
            puntosDeMunicipio.put(new Point(167, 108), "El Doncello");
            puntosDeMunicipio.put(new Point(174, 130), "El Doncello");
            
            puntosDeMunicipio.put(new Point(325, 371), "Cartagena del Chaira");
            
            puntosDeMunicipio.put(new Point(563, 483), "Solano");
            puntosDeMunicipio.put(new Point(249, 402), "Solano");
            
            puntosDeMunicipio.put(new Point(161, 176), "El Paujìl");
            puntosDeMunicipio.put(new Point(175, 227), "El Paujìl");
            
            puntosDeMunicipio.put(new Point(202, 167), "Puerto Rico");
            puntosDeMunicipio.put(new Point(186, 106), "Puerto Rico");
            
            puntosDeMunicipio.put(new Point(151, 186), "Montañita");
            puntosDeMunicipio.put(new Point(177, 267), "Montañita");
            puntosDeMunicipio.put(new Point(150, 130), "Montañita");
            
            puntosDeMunicipio.put(new Point(115, 198), "Florencia");
            
            puntosDeMunicipio.put(new Point(70, 227), "Belèn");
            
            puntosDeMunicipio.put(new Point(34, 261), "San Jose del Fragua");
            
            puntosDeMunicipio.put(new Point(61, 296), "Curillo");
            
            puntosDeMunicipio.put(new Point(71, 275), "Albania");
            
            puntosDeMunicipio.put(new Point(97, 323), "Solita");
            
            puntosDeMunicipio.put(new Point(123, 324), "Solita");
            
            puntosDeMunicipio.put(new Point(110, 292), "Valparaiso");
            
            puntosDeMunicipio.put(new Point(108, 251), "Morelia");
            
            puntosDeMunicipio.put(new Point(151, 285), "Milan");
            
           
            
          
            // Agregar MouseListener al jLabel6
            jLabel6.addMouseMotionListener(new MouseMotionAdapter() {
                @Override
                public void mouseMoved(MouseEvent e) {
                    currentX = e.getX();
                    currentY = e.getY();
                    updateHighlight();
                }
            });
            
            // Herramienta para definir puntos de referencia
            jLabel6.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    if (e.isControlDown() && e.isShiftDown()) {
                        String nombre = javax.swing.JOptionPane.showInputDialog(
                            "Nombre del municipio para el punto (" + e.getX() + "," + e.getY() + "):");
                        if (nombre != null && !nombre.trim().isEmpty()) {
                            puntosDeMunicipio.put(new Point(e.getX(), e.getY()), nombre);
                            javax.swing.JOptionPane.showMessageDialog(null, "Punto para " + nombre + " registrado.");
                        }
                    } else if (e.isAltDown()) {
                        // Mostrar todos los puntos registrados
                        StringBuilder info = new StringBuilder("Puntos registrados:\n");
                        for (Map.Entry<Point, String> entry : puntosDeMunicipio.entrySet()) {
                            Point p = entry.getKey();
                            info.append(String.format("%s: (%d, %d)\n", entry.getValue(), p.x, p.y));
                        }
                        javax.swing.JOptionPane.showMessageDialog(null, info.toString());
                    }
                }
            });
            
            // Hacer que jLabel6 sea personalizado para mostrar el resaltado
            jLabel6.setIcon(new ImageIcon(mapImage) {
                @Override
                public void paintIcon(Component c, Graphics g, int x, int y) {
                    super.paintIcon(c, g, x, y);
                    if (highlightedImage != null) {
                        g.drawImage(highlightedImage, x, y, c);
                    }
                    
                    // Mostrar los puntos de referencia solo cuando Control está presionado
                    if (controlKeyPressed) {
                        g.setColor(Color.BLUE);
                        for (Point p : puntosDeMunicipio.keySet()) {
                            g.fillOval(p.x - 3, p.y - 3, 6, 6);
                        }
                    }
                }
            });
            
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    private BufferedImage detectarBordes(BufferedImage imagen) {
        int width = imagen.getWidth();
        int height = imagen.getHeight();
        BufferedImage result = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        
        int umbral = 50; // Valor umbral para detección de bordes
        
        // Matriz para el operador de Sobel (detección de bordes)
        int[][] sobelX = {{-1, 0, 1}, {-2, 0, 2}, {-1, 0, 1}};
        int[][] sobelY = {{-1, -2, -1}, {0, 0, 0}, {1, 2, 1}};
        
        for (int y = 1; y < height - 1; y++) {
            for (int x = 1; x < width - 1; x++) {
                // Aplicar operador Sobel
                int gx = 0;
                int gy = 0;
                
                for (int i = -1; i <= 1; i++) {
                    for (int j = -1; j <= 1; j++) {
                        int rgb = imagen.getRGB(x + i, y + j);
                        int gray = (int)(0.299 * ((rgb >> 16) & 0xFF) + 
                                         0.587 * ((rgb >> 8) & 0xFF) + 
                                         0.114 * (rgb & 0xFF));
                        
                        gx += gray * sobelX[i+1][j+1];
                        gy += gray * sobelY[i+1][j+1];
                    }
                }
                
                // Magnitud del gradiente
                int magnitude = (int)Math.sqrt(gx * gx + gy * gy);
                magnitude = Math.min(255, magnitude);
                
                // Umbral para detectar bordes
                if (magnitude > umbral) {
                    result.setRGB(x, y, new Color(0, 0, 0).getRGB());
                } else {
                    result.setRGB(x, y, new Color(255, 255, 255, 0).getRGB()); // Transparente
                }
            }
        }
        
        return result;
    }
    
    private void updateHighlight() {
    if (mapImage != null && currentX >= 0 && currentY >= 0 &&
        currentX < mapImage.getWidth() && currentY < mapImage.getHeight()) {
        
        // Comprueba si el punto está dentro de un municipio
        String newMunicipio = encontrarMunicipio(currentX, currentY);
        
        if ((newMunicipio == null && municipioActual != null) || 
            (newMunicipio != null && !newMunicipio.equals(municipioActual))) {
            municipioActual = newMunicipio;
            highlightRegion();
            jLabel6.repaint();
            
            // Actualizar el panel flotante
            if (municipioActual != null) {
                labelNombreMunicipio.setText(municipioActual);
                panelFlotante.setVisible(true);
                
                // Get the position relative to the JLabel
                Point labelPos = jLabel6.getLocationOnScreen();
                // Calculate where the panel should appear relative to the cursor
                int panelX = currentX + 20;
                int panelY = currentY + 20;
                
                // Convert to the layered pane's coordinate system
                Point convertedPoint = SwingUtilities.convertPoint(
                    jLabel6, panelX, panelY, getLayeredPane());
                
                // Ensure panel doesn't go off-screen
                Dimension panelSize = panelFlotante.getPreferredSize();
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                Point framePos = getLocationOnScreen();
                
                if (labelPos.x + panelX + panelSize.width > framePos.x + getWidth()) {
                    panelX = currentX - panelSize.width - 20;
                }
                if (labelPos.y + panelY + panelSize.height > framePos.y + getHeight()) {
                    panelY = currentY - panelSize.height - 20;
                }
                
                // Position the panel in the layered pane
                panelFlotante.setBounds(
                    convertedPoint.x, 
                    convertedPoint.y, 
                    panelSize.width, 
                    panelSize.height
                );
                
                panelFlotante.revalidate();
                panelFlotante.repaint();
            } else {
                panelFlotante.setVisible(false);
            }
        }
    }
}
    
    private String encontrarMunicipio(int x, int y) {
        // Busca el punto de referencia más cercano que no esté separado por un borde
        String resultado = null;
        double distanciaMinima = Double.MAX_VALUE;
        
        for (Map.Entry<Point, String> entry : puntosDeMunicipio.entrySet()) {
            Point punto = entry.getKey();
            
            // Verifica si hay un borde entre el punto actual y el punto de referencia
            if (!hayBordeEntre(x, y, punto.x, punto.y)) {
                double distancia = punto.distance(x, y);
                if (distancia < distanciaMinima) {
                    distanciaMinima = distancia;
                    resultado = entry.getValue();
                }
            }
        }
        
        return resultado;
    }
    
    private boolean hayBordeEntre(int x1, int y1, int x2, int y2) {
        // Algoritmo de Bresenham para trazar una línea entre dos puntos
        // y verificar si cruza algún borde
        int dx = Math.abs(x2 - x1);
        int dy = Math.abs(y2 - y1);
        int sx = x1 < x2 ? 1 : -1;
        int sy = y1 < y2 ? 1 : -1;
        int err = dx - dy;
        
        int saltoPuntos = 2; // Verificar cada 2 puntos para permitir "saltar" pequeños bordes
        int contador = 0;
        
        while (x1 != x2 || y1 != y2) {
            contador++;
            
            // Solo verificar cada 'saltoPuntos'
            if (contador % saltoPuntos == 0) {
                // Verifica si este punto es un borde
                if (x1 >= 0 && y1 >= 0 && x1 < bordersImage.getWidth() && y1 < bordersImage.getHeight()) {
                    int rgb = bordersImage.getRGB(x1, y1);
                    if (rgb == Color.BLACK.getRGB()) {
                        return true; // Encontró un borde
                    }
                }
            }
            
            int e2 = 2 * err;
            if (e2 > -dy) {
                err -= dy;
                x1 += sx;
            }
            if (e2 < dx) {
                err += dx;
                y1 += sy;
            }
        }
        
        return false; // No hay borde entre los puntos
    }
    
    private void highlightRegion() {
        // Limpia la imagen de resaltado
        Graphics2D g2d = highlightedImage.createGraphics();
        g2d.setComposite(AlphaComposite.Clear);
        g2d.fillRect(0, 0, highlightedImage.getWidth(), highlightedImage.getHeight());
        g2d.dispose();
        
        if (municipioActual == null) {
            return;
        }
        
        // Encuentra todos los puntos de referencia para el municipio actual
        for (Map.Entry<Point, String> entry : puntosDeMunicipio.entrySet()) {
            if (entry.getValue().equals(municipioActual)) {
                Point semilla = entry.getKey();
                // Usa flood fill para rellenar la región delimitada por bordes
                floodFillRegion(semilla.x, semilla.y);
            }
        }
    }
    
    private void floodFillRegion(int x, int y) {
        int width = mapImage.getWidth();
        int height = mapImage.getHeight();
        boolean[][] visitado = new boolean[width][height];
        
        // Cola para el algoritmo de flood fill
        Queue<Point> queue = new LinkedList<>();
        queue.add(new Point(x, y));
        visitado[x][y] = true;
        
        while (!queue.isEmpty()) {
            Point p = queue.remove();
            
            // Colorea este punto
            highlightedImage.setRGB(p.x, p.y, HIGHLIGHT_COLOR.getRGB());
            
            // Verificar 8 direcciones para mejor relleno
            int[][] dirs = {
                {0, -1}, {1, -1}, {1, 0}, {1, 1}, 
                {0, 1}, {-1, 1}, {-1, 0}, {-1, -1}
            };
            
            for (int[] dir : dirs) {
                int nx = p.x + dir[0];
                int ny = p.y + dir[1];
                
                if (nx >= 0 && nx < width && ny >= 0 && ny < height && !visitado[nx][ny]) {
                    // Si este punto no es un borde, añádelo a la cola
                    int rgb = bordersImage.getRGB(nx, ny);
                    if (rgb != Color.BLACK.getRGB()) {
                        queue.add(new Point(nx, ny));
                        visitado[nx][ny] = true;
                    }
                }
            }
        }
    }
    
    private void setupKeyListener() {
        // Añadimos key listeners para detectar cuando Control está presionado
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {
            @Override
            public boolean dispatchKeyEvent(KeyEvent e) {
                // Actualizar el estado de la tecla Control
                controlKeyPressed = e.isControlDown();
                // Solicitar repintado del componente cuando el estado de Control cambia
                if (jLabel6 != null) {
                    jLabel6.repaint();
                }
                return false; // Dejar que el evento siga su curso normal
            }
        });
    }
}
