/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador_Doncello;
import static Vista.Vista_Municipio_Florencia.aplicarEstiloEstetico;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author COMPUCENTER-DM
 */
public class VIsta_Municipio_Doncello extends javax.swing.JFrame {

    Controlador_Doncello controlador;
    public VIsta_Municipio_Doncello() {
        initComponents();
        
        controlador = new Controlador_Doncello(this);
        foto(lbl_foto, "src\\img\\doncello.png");
        aplicarEstiloEstetico(btn_Anayancito);
        aplicarEstiloEstetico(btn_Fin_Estres);
        aplicarEstiloEstetico(btn_Munay);
        aplicarEstiloEstetico(btn_Volver);
    }
    public JButton getBtn_Anayancito() {
            return btn_Anayancito;
    }

    public JButton getBtn_Fin_Estres() {
        return btn_Fin_Estres;
    }

    public JButton getBtn_Munay() {
        return btn_Munay;
    }
    

    public void foto(JLabel label, String ruta) {
        ImageIcon icon = new ImageIcon("src\\img\\doncello.png");
        Image img = icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Fin_Estres = new javax.swing.JButton();
        btn_Anayancito = new javax.swing.JButton();
        btn_Munay = new javax.swing.JButton();
        btn_Volver = new javax.swing.JButton();
        lbl_foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(320, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Fin_Estres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/punto interes.png"))); // NOI18N
        btn_Fin_Estres.setText("Cascada Fin Del Estres ");
        getContentPane().add(btn_Fin_Estres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 210, 40));

        btn_Anayancito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/punto interes.png"))); // NOI18N
        btn_Anayancito.setText("Cascada Anayancito");
        btn_Anayancito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AnayancitoMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Anayancito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 220, 50));

        btn_Munay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/punto interes.png"))); // NOI18N
        btn_Munay.setText("Tierras Munay");
        getContentPane().add(btn_Munay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 200, 40));

        btn_Volver.setText("Volver");
        btn_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_VolverMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        lbl_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doncello.png"))); // NOI18N
        lbl_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AnayancitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnayancitoMouseClicked

    }//GEN-LAST:event_btn_AnayancitoMouseClicked

    private void btn_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VolverMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_VolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VIsta_Municipio_Doncello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VIsta_Municipio_Doncello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VIsta_Municipio_Doncello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VIsta_Municipio_Doncello.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VIsta_Municipio_Doncello().setVisible(true);
                        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Anayancito;
    public javax.swing.JButton btn_Fin_Estres;
    public javax.swing.JButton btn_Munay;
    public javax.swing.JButton btn_Volver;
    private javax.swing.JLabel lbl_foto;
    // End of variables declaration//GEN-END:variables
}
