/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Controlador.Controlador_Puerto_Rico;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;

/**
 *
 * @author COMPUCENTER-DM
 */
public class Vista_Municipio_Puerto_Rico extends javax.swing.JFrame {

  Controlador_Puerto_Rico controlador;
    public Vista_Municipio_Puerto_Rico() {
        initComponents();
        controlador = new Controlador_Puerto_Rico(this);
        foto(lbl_foto, "src\\img\\ puerto rico.png");
        aplicarEstiloEstetico(btn_Pozo_Frio);
        aplicarEstiloEstetico(btn_Salto_Tigre);
        aplicarEstiloEstetico(btn_Cascada_Salado);
        aplicarEstiloEstetico(btn_Volver);
    }
    public JButton getBtn_Pozo_Frio() {
            return btn_Pozo_Frio;
    }

    public JButton getBtn_Salto_Tigre() {
        return btn_Salto_Tigre;
    }

    public JButton getBtn_Cascada_Salado() {
        return btn_Cascada_Salado;
    }
    
    public static void aplicarEstiloEstetico(JButton boton) {
        boton.setFont(new Font("Segoe UI", Font.BOLD, 16));
        boton.setForeground(new Color(33, 37, 41)); // Gris oscuro sobrio
        boton.setBackground(new Color(144, 238, 144)); // Verde suave estilo SENA
        boton.setFocusPainted(false);
        boton.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        boton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        boton.setOpaque(false);

        boton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                boton.setBackground(new Color(124, 218, 124)); // Un verde un poco más intenso
                boton.repaint();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                boton.setBackground(new Color(144, 238, 144));
                boton.repaint();
            }
        });

        // 🎨 Estilo gráfico personalizado (minimalista y redondeado)
        boton.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, JComponent c) {
                Graphics2D g2 = (Graphics2D) g.create();
                int w = c.getWidth();
                int h = c.getHeight();

                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(boton.getBackground());
                g2.fillRoundRect(0, 0, w, h, 30, 30); // Bordes redondeados

                g2.dispose();
                super.paint(g, c);
            }
        });
    }

    public void foto(JLabel label, String ruta) {
        ImageIcon icon = new ImageIcon("src\\img\\puerto rico.png");
        Image img = icon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Cascada_Salado = new javax.swing.JButton();
        btn_Salto_Tigre = new javax.swing.JButton();
        btn_Pozo_Frio = new javax.swing.JButton();
        btn_Volver = new javax.swing.JButton();
        lbl_foto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(320, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Cascada_Salado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/punto interes.png"))); // NOI18N
        btn_Cascada_Salado.setText("Cascada El Salado ");
        getContentPane().add(btn_Cascada_Salado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 60, 200, 40));

        btn_Salto_Tigre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/punto interes.png"))); // NOI18N
        btn_Salto_Tigre.setText("Salto Del Tigre");
        getContentPane().add(btn_Salto_Tigre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 200, 40));

        btn_Pozo_Frio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/punto interes.png"))); // NOI18N
        btn_Pozo_Frio.setText("Pozo Montefrio ");
        btn_Pozo_Frio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Pozo_FrioMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Pozo_Frio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 200, 50));

        btn_Volver.setText("Volver");
        btn_Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_VolverMouseClicked(evt);
            }
        });
        getContentPane().add(btn_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        lbl_foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/doncello.png"))); // NOI18N
        lbl_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Pozo_FrioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Pozo_FrioMouseClicked

    }//GEN-LAST:event_btn_Pozo_FrioMouseClicked

    private void btn_VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_VolverMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_VolverMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Municipio_Puerto_Rico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Municipio_Puerto_Rico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Municipio_Puerto_Rico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Municipio_Puerto_Rico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Municipio_Puerto_Rico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Cascada_Salado;
    public javax.swing.JButton btn_Pozo_Frio;
    public javax.swing.JButton btn_Salto_Tigre;
    public javax.swing.JButton btn_Volver;
    private javax.swing.JLabel lbl_foto;
    // End of variables declaration//GEN-END:variables
}
