/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.controlador_sitios_turisticos;
import java.awt.Image;
import javax.swing.ImageIcon;
import Modelo.modelo_sitios_turisticos;

/**
 *
 * @author userx
 */
public class vista_sitios_turisticos extends javax.swing.JFrame {

    /**
     * Creates new form vista_sitios_turisticos
     */
    String foto ="C:\\Users\\userx\\Documents\\Java ADSO\\SitiosTuristicos\\src\\imagenes\\fondo.png";
    Controlador.controlador_sitios_turisticos controlador;
    Modelo.modelo_sitios_turisticos modelo = new Modelo.modelo_sitios_turisticos();
    boolean click = false;
    public int numeroEstrella = 0;
    
    public vista_sitios_turisticos(String sitio_turistico) {
        initComponents();
        

        controlador = new controlador_sitios_turisticos(this, modelo, sitio_turistico);
        controlador.iniciar();
    
        cargarFondo();
        
    }
    
    public void cargarFondo()
    {
        ImageIcon icon = new ImageIcon(foto);

        Image image = icon.getImage();

        Image scaledImage = image.getScaledInstance(fondo.getWidth(), fondo.getHeight(), Image.SCALE_SMOOTH);

        ImageIcon scaledIcon = new ImageIcon(scaledImage);
      
        fondo.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JLabel();
        lblNombre_sitio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        estrella5 = new javax.swing.JLabel();
        estrella1 = new javax.swing.JLabel();
        estrella2 = new javax.swing.JLabel();
        estrella3 = new javax.swing.JLabel();
        estrella4 = new javax.swing.JLabel();
        Servicios = new javax.swing.JPanel();
        vista360 = new javax.swing.JButton();
        calificar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(245, 245, 245));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img.setText("jLabel1");
        img.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 111, 990, 279));

        lblNombre_sitio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        lblNombre_sitio.setText("jLabel1");
        getContentPane().add(lblNombre_sitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 28, 487, 60));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver al mapa");
        jButton1.setBorder(null);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 33, 194, 60));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDescripcion.setText("jLabel1");
        lblDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 383, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("DESCRIPCION DEL LUGAR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Servicios disponibles");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, -1, -1));

        estrella5.setText("jLabel2");
        estrella5.setPreferredSize(new java.awt.Dimension(50, 50));
        estrella5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estrella5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estrella5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estrella5MouseExited(evt);
            }
        });
        getContentPane().add(estrella5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 820, 50, 50));

        estrella1.setText("jLabel2");
        estrella1.setPreferredSize(new java.awt.Dimension(50, 50));
        estrella1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estrella1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estrella1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estrella1MouseExited(evt);
            }
        });
        getContentPane().add(estrella1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 820, 50, 50));

        estrella2.setText("jLabel2");
        estrella2.setPreferredSize(new java.awt.Dimension(50, 50));
        estrella2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estrella2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estrella2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estrella2MouseExited(evt);
            }
        });
        getContentPane().add(estrella2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 820, 50, 50));

        estrella3.setText("jLabel2");
        estrella3.setPreferredSize(new java.awt.Dimension(50, 50));
        estrella3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estrella3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estrella3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estrella3MouseExited(evt);
            }
        });
        getContentPane().add(estrella3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 820, 50, 50));

        estrella4.setText("jLabel2");
        estrella4.setPreferredSize(new java.awt.Dimension(50, 50));
        estrella4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estrella4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estrella4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estrella4MouseExited(evt);
            }
        });
        getContentPane().add(estrella4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 820, 50, 50));

        Servicios.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ServiciosLayout = new javax.swing.GroupLayout(Servicios);
        Servicios.setLayout(ServiciosLayout);
        ServiciosLayout.setHorizontalGroup(
            ServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        ServiciosLayout.setVerticalGroup(
            ServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        getContentPane().add(Servicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 310, -1));

        vista360.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        vista360.setText("vista 360°");
        getContentPane().add(vista360, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, -1, -1));

        calificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        calificar.setText("Calificar");
        getContentPane().add(calificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 880, -1, -1));

        fondo.setBackground(new java.awt.Color(245, 245, 245));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 950));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estrella1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella1MouseEntered
        modelo.cargarEstrellas(this, false);
        modelo.estrellaCambiarColor(this, 1);
    }//GEN-LAST:event_estrella1MouseEntered

    private void estrella2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella2MouseEntered
        modelo.cargarEstrellas(this, false);
        modelo.estrellaCambiarColor(this, 2);
    }//GEN-LAST:event_estrella2MouseEntered

    private void estrella3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella3MouseEntered
        modelo.cargarEstrellas(this, false);
        modelo.estrellaCambiarColor(this, 3);
    }//GEN-LAST:event_estrella3MouseEntered

    private void estrella4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella4MouseClicked
        modelo.cargarEstrellas(this, false);
        if(click == true && (numeroEstrella != 4))
        {
            modelo.cargarEstrellas(this, false);
            modelo.estrellaCambiarColor(this, 4);
            numeroEstrella = 4;
        }
        else if(click == true)
        {
            click = false;
            numeroEstrella = 0;
        }
        else
        {
            click = true;
            modelo.estrellaCambiarColor(this, 4);
            numeroEstrella = 4;
        }
    }//GEN-LAST:event_estrella4MouseClicked

    private void estrella4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella4MouseEntered
        modelo.cargarEstrellas(this, false);
        modelo.estrellaCambiarColor(this, 4);
    }//GEN-LAST:event_estrella4MouseEntered

    private void estrella5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella5MouseEntered
        modelo.cargarEstrellas(this, false);
        modelo.estrellaCambiarColor(this, 5);
    }//GEN-LAST:event_estrella5MouseEntered

    private void estrella1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella1MouseExited
        modelo.cargarEstrellas(this, false);
        if(click)
        {
            modelo.estrellaCambiarColor(this, numeroEstrella);
        }
    }//GEN-LAST:event_estrella1MouseExited

    private void estrella2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella2MouseExited
        modelo.cargarEstrellas(this, false);
        if(click)
        {
            modelo.estrellaCambiarColor(this, numeroEstrella);
        }
    }//GEN-LAST:event_estrella2MouseExited

    private void estrella3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella3MouseExited
        modelo.cargarEstrellas(this, false);
        if(click)
        {
            modelo.estrellaCambiarColor(this, numeroEstrella);
        }
    }//GEN-LAST:event_estrella3MouseExited

    private void estrella4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella4MouseExited
        modelo.cargarEstrellas(this, false);
        if(click)
        {
            modelo.estrellaCambiarColor(this, numeroEstrella);
        }
    }//GEN-LAST:event_estrella4MouseExited

    private void estrella5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella5MouseExited
        modelo.cargarEstrellas(this, false);
        if(click)
        {
            modelo.estrellaCambiarColor(this, numeroEstrella);
        }
    }//GEN-LAST:event_estrella5MouseExited

    private void estrella1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella1MouseClicked
        modelo.cargarEstrellas(this, false);
        if(click == true && (numeroEstrella != 1))
        {
            modelo.cargarEstrellas(this, false);
            modelo.estrellaCambiarColor(this, 1);
            numeroEstrella = 1;
        }
        else if(click == true)
        {
            click = false;
            numeroEstrella = 0;
        }
        else
        {
            click = true;
            modelo.estrellaCambiarColor(this, 1);
            numeroEstrella = 1;
        }
    }//GEN-LAST:event_estrella1MouseClicked

    private void estrella2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella2MouseClicked
        modelo.cargarEstrellas(this, false);
        if(click == true && (numeroEstrella != 2))
        {
            modelo.cargarEstrellas(this, false);
            modelo.estrellaCambiarColor(this, 2);
            numeroEstrella = 2;
        }
        else if(click == true)
        {
            click = false;
            numeroEstrella = 0;
        }
        else
        {
            click = true;
            modelo.estrellaCambiarColor(this, 2);
            numeroEstrella = 2;
        }
    }//GEN-LAST:event_estrella2MouseClicked

    private void estrella3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella3MouseClicked
        modelo.cargarEstrellas(this, false);
        if(click == true && (numeroEstrella != 3))
        {
            modelo.cargarEstrellas(this, false);
            modelo.estrellaCambiarColor(this, 3);
            numeroEstrella = 3;
        }
        else if(click == true)
        {
            click = false;
            numeroEstrella = 0;
        }
        else
        {
            click = true;
            modelo.estrellaCambiarColor(this, 3);
            numeroEstrella = 3;
        }
    }//GEN-LAST:event_estrella3MouseClicked

    private void estrella5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estrella5MouseClicked
        modelo.cargarEstrellas(this, false);
        if(click == true && (numeroEstrella != 5))
        {
            modelo.cargarEstrellas(this, false);
            modelo.estrellaCambiarColor(this, 5);
            numeroEstrella = 5;
        }
        else if(click == true)
        {
            click = false;
            numeroEstrella = 0;
        }
        else
        {
            click = true;
            modelo.estrellaCambiarColor(this, 5);
            numeroEstrella = 5;
        }
    }//GEN-LAST:event_estrella5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vista_sitios_turisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vista_sitios_turisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vista_sitios_turisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vista_sitios_turisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vista_sitios_turisticos("CTierras del Munay").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Servicios;
    public javax.swing.JButton calificar;
    public javax.swing.JLabel estrella1;
    public javax.swing.JLabel estrella2;
    public javax.swing.JLabel estrella3;
    public javax.swing.JLabel estrella4;
    public javax.swing.JLabel estrella5;
    public javax.swing.JLabel fondo;
    public javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel lblDescripcion;
    public javax.swing.JLabel lblNombre_sitio;
    public javax.swing.JButton vista360;
    // End of variables declaration//GEN-END:variables
}
